# fly.toml app configuration file generated for meshmonitor on 2025-12-26T20:09:22-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "meshmonitor"
primary_region = "ord"

[build]

[env]
  DATABASE_PATH = "/data/meshmonitor.db"
  FLASK_HOST = "0.0.0.0"
  FLASK_PORT = "5000"
  MQTT_BROKER_HOST = "127.0.0.1"
  MQTT_BROKER_PORT = "1883"
  MQTT_TOPIC = "msh/US/#"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  protocol = "tcp"
  internal_port = 8883

  [[services.ports]]
    port = 8883
    handlers = ["tls"]

[[vm]]
  cpus = 1
  memory = "1gb"
  cpu_kind = "shared"

[deploy]
  strategy = "immediate"
